### ISSUE TITLE
Check base64 encoding of external assets

### ISSUE THREAD

**Issue by flo-sch** [subbly/installer#3]
Assets called by assets file such as fonts by the CSS should be converted in base64 (inline in the style).

Gulp-base64 does not currently seem to work, we'll need to fix it or look for alternatives.

**Comment by flo-sch** [comment]
I found another npm plugin,
However the CSS exported size is really huge (more than 30 Mo)...

Any idea?
@nicolas-brousse

**Comment by nicolas-brousse** [comment]
Not sure we can do something special because fonts take a lot of place.

``` sh
$ du -hs src/Subbly/Installer/Resources/views/assets/fonts 
 26M    src/Subbly/Installer/Resources/views/assets/fonts
```

**Comment by flo-sch** [comment]
Actually it's insane, I will have to reduce it (all formats are probably not needed) ;

I've got a memory error while trying to generate the archiver which might be related... Is it working for you?

**Comment by nicolas-brousse** [comment]
Okay. 

About the memory error. Are you talking about the build command. 
If yes I do a fix during the day on the master branch.

**Comment by flo-sch** [comment]
Yes, that's it. If you need precisions I can send you the trace ?

**Comment by nicolas-brousse** [comment]
Please try first with the master branch first. And if the error is still here, open a new issue.
